/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appbiblioteca;

/**
 *
 * @author accpc
 */

import javax.swing.ImageIcon;

public class formMain extends javax.swing.JFrame {

    /**
     * Creates new form formMain
     */
    public formMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBaseMain = new javax.swing.JPanel();
        jPMenu = new javax.swing.JPanel();
        jLTitoloMenu = new javax.swing.JLabel();
        jBrLibro = new javax.swing.JButton();
        jBPrestito = new javax.swing.JButton();
        jLRegistrazioni = new javax.swing.JLabel();
        jLRichieste = new javax.swing.JLabel();
        jBrUtente = new javax.swing.JButton();
        jBRestiituzione = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menù ");
        setResizable(false);

        jBaseMain.setBackground(new java.awt.Color(51, 0, 0));

        jPMenu.setBackground(new java.awt.Color(255, 204, 102));
        jPMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 5));

        jLTitoloMenu.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 36)); // NOI18N
        jLTitoloMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTitoloMenu.setText("Menù principale");

        javax.swing.GroupLayout jPMenuLayout = new javax.swing.GroupLayout(jPMenu);
        jPMenu.setLayout(jPMenuLayout);
        jPMenuLayout.setHorizontalGroup(
            jPMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLTitoloMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPMenuLayout.setVerticalGroup(
            jPMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLTitoloMenu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jBrLibro.setBackground(new java.awt.Color(255, 204, 102));
        jBrLibro.setIcon(new ImageIcon("book-stack.png"));
        jBrLibro.setText("Registra libro");
        jBrLibro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBrLibro.setIconTextGap(10);
        jBrLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBrLibroActionPerformed(evt);
            }
        });

        jBPrestito.setBackground(new java.awt.Color(255, 204, 102));
        jBPrestito.setIcon(new ImageIcon("remove.png"));
        jBPrestito.setText("Prestito libro");
        jBPrestito.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBPrestito.setIconTextGap(10);
        jBPrestito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPrestitoActionPerformed(evt);
            }
        });

        jLRegistrazioni.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        jLRegistrazioni.setForeground(new java.awt.Color(255, 204, 102));
        jLRegistrazioni.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLRegistrazioni.setText("Registrazioni");

        jLRichieste.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        jLRichieste.setForeground(new java.awt.Color(255, 204, 102));
        jLRichieste.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLRichieste.setText("Richieste");

        jBrUtente.setBackground(new java.awt.Color(255, 204, 102));
        jBrUtente.setIcon(new ImageIcon("user.png"));
        jBrUtente.setText("Registra utente");
        jBrUtente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBrUtente.setIconTextGap(10);
        jBrUtente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBrUtenteActionPerformed(evt);
            }
        });

        jBRestiituzione.setBackground(new java.awt.Color(255, 204, 102));
        jBRestiituzione.setIcon(new ImageIcon("add.png"));
        jBRestiituzione.setText("Restituzione libro");
        jBRestiituzione.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBRestiituzione.setIconTextGap(10);
        jBRestiituzione.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRestiituzioneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jBaseMainLayout = new javax.swing.GroupLayout(jBaseMain);
        jBaseMain.setLayout(jBaseMainLayout);
        jBaseMainLayout.setHorizontalGroup(
            jBaseMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBaseMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jBaseMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBPrestito, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLRegistrazioni, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBrLibro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLRichieste, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBRestiituzione, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBrUtente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jBaseMainLayout.setVerticalGroup(
            jBaseMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBaseMainLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jPMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLRegistrazioni)
                .addGap(18, 18, 18)
                .addComponent(jBrLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBrUtente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLRichieste)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBPrestito, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBRestiituzione, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBaseMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBaseMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBrLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBrLibroActionPerformed
        (new formAnagraficaLibro()).setVisible(true);
    }//GEN-LAST:event_jBrLibroActionPerformed

    private void jBPrestitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPrestitoActionPerformed
        (new formPrestito()).setVisible(true);
    }//GEN-LAST:event_jBPrestitoActionPerformed

    private void jBrUtenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBrUtenteActionPerformed
        (new formAnagraficaUtente()).setVisible(true);
    }//GEN-LAST:event_jBrUtenteActionPerformed

    private void jBRestiituzioneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRestiituzioneActionPerformed
        (new formRestituzione()).setVisible(true);
    }//GEN-LAST:event_jBRestiituzioneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows Classic".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBPrestito;
    private javax.swing.JButton jBRestiituzione;
    private javax.swing.JPanel jBaseMain;
    private javax.swing.JButton jBrLibro;
    private javax.swing.JButton jBrUtente;
    private javax.swing.JLabel jLRegistrazioni;
    private javax.swing.JLabel jLRichieste;
    private javax.swing.JLabel jLTitoloMenu;
    private javax.swing.JPanel jPMenu;
    // End of variables declaration//GEN-END:variables
}
